### ISSUE TITLE
CSS values

### ISSUE THREAD

**Issue by Default4152** [jengreen21/f1-3-c2p1-colmar-academy#3]
Important for errors - In a few places in style.css (L139, L140, L146, L147, L148) have errors as the values aren't correct for the property type.

Information regarding which values are available for `align-items`, `align-content`, and `justify-content`:
https://developer.mozilla.org/en-US/docs/Web/CSS/align-items
https://developer.mozilla.org/en-US/docs/Web/CSS/align-content
https://developer.mozilla.org/en-US/docs/Web/CSS/justify-content

**Comment by jengreen21** [comment]
These have been fixed.  Thanks for the reminder on where to get information on the values.
