### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by Default4152** [jengreen21/f1-3-c2p1-colmar-academy#5]
Grade: **Needs Improvement**

I really like how your HTML is formatted! It's very clean and easy to read over. On top of this you used semantic elements and alt attributes which are great for things like accessibility. There are quite a few errors in the style.css file with the property values being incorrect or syntax errors (typos) like a semicolon instead of a colon on line 406. A lot of these errors can be avoided by using something like a CSS validator or CSS linter. Here's a great tool you can paste your CSS into to get instant feedback: https://jigsaw.w3.org/css-validator/#validate_by_input

I would try to validate your CSS and then fix all of the errors it comes up with. After that you can try to fix any additional problems associated with how the page should look.

**Comment by jengreen21** [comment]
Thank you for your review!   I wish I had known about the css validator earlier in the class.  Did I miss it somewhere?
